### ISSUE TITLE
JsonMappingException: Numeric value (1708813219016) out of range of int (-2147483648 - 2147483647)

### ISSUE THREAD

**Issue by FabianFrischmann** [sonallux/spotify-web-api-java#259]
Hi, I tried to access the user's current playing song (and yes I have spotify playing music while testing) and get the following exception while trying to do so

`Exception in thread "main" de.sonallux.spotify.api.SpotifyApiException: Failed to make api call
	at de.sonallux.spotify.api.http.ApiCall.execute(ApiCall.java:86)
	at me.wasn325.PlayListTest.main(PlayListTest.java:161)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Numeric value (1708813219016) out of range of int (-2147483648 - 2147483647)
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 2, column: 30] (through reference chain: de.sonallux.spotify.api.models.CurrentlyPlaying["timestamp"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:402)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:361)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1937)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:312)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:342)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4899)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3891)
	at de.sonallux.spotify.api.http.ApiCall.parseResponseBody(ApiCall.java:123)
	at de.sonallux.spotify.api.http.ApiCall.parseResponse(ApiCall.java:104)
	at de.sonallux.spotify.api.http.AuthorizedApiCall.parseResponse(AuthorizedApiCall.java:25)
	at de.sonallux.spotify.api.http.ApiCall.executeCall(ApiCall.java:78)
	at de.sonallux.spotify.api.http.ApiCall.execute(ApiCall.java:84)
	... 1 more
Caused by: com.fasterxml.jackson.core.exc.InputCoercionException: Numeric value (1708813219016) out of range of int (-2147483648 - 2147483647)
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 2, column: 30]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportInputCoercion(ParserMinimalBase.java:640)
	at com.fasterxml.jackson.core.base.ParserMinimalBase.reportOverflowInt(ParserMinimalBase.java:609)
	at com.fasterxml.jackson.core.base.ParserBase.convertNumberToInt(ParserBase.java:1038)
	at com.fasterxml.jackson.core.base.ParserBase._parseIntValue(ParserBase.java:962)
	at com.fasterxml.jackson.core.base.ParserBase.getIntValue(ParserBase.java:768)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:526)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:506)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:310)
	... 10 more`

Any other request works normally (as I can tell currently). Do you have any Idea why the mapping exception happens?

By the way: The code triggering this error looks like this

`var song = spotifyApi.getPlayerApi()
                .getUsersCurrentlyPlayingTrack()
                .build()
                .execute();`

**Comment by sonallux** [comment]
@FabianFrischmann thanks for reporting this issue 👍 It will be fixed in version `4.2.0`, which will be available soon on Maven central.
